// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCzyDRH77lVlmxMMb8mL4nuSqe4gFdpc',
    appId: '1:379224027061:web:986136a638716175eb33fc',
    messagingSenderId: '379224027061',
    projectId: 'ecommerce-pesa-9815a',
    authDomain: 'ecommerce-pesa-9815a.firebaseapp.com',
    storageBucket: 'ecommerce-pesa-9815a.appspot.com',
    measurementId: 'G-38YPW8Q3YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTsPtYlsgszoGhZHTCAYHoYG8W4D_ttCI',
    appId: '1:379224027061:android:bb27a73c4f8661baeb33fc',
    messagingSenderId: '379224027061',
    projectId: 'ecommerce-pesa-9815a',
    storageBucket: 'ecommerce-pesa-9815a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuTaDipYvN5G9d06v3qyIWTznSV4KqY_Y',
    appId: '1:379224027061:ios:941d89980ad316caeb33fc',
    messagingSenderId: '379224027061',
    projectId: 'ecommerce-pesa-9815a',
    storageBucket: 'ecommerce-pesa-9815a.appspot.com',
    iosClientId: '379224027061-c2oflccnc1cka26a8r4s87pa3ovsnsbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommercePesacoder',
  );
}
